apiVersion: v1
kind: Pod #kind of obj
metadata: 
 name: myfirstpod #name of obj
 labels:
  app: myFirstpod
  type: network 
spec: # the pod require a container
 containers: #create a container
  - name: nginx # name of container
    image: nginx #img of container in dockerhub
    #ports: here expose our ports we use a port 
    #- containerPort:80 on which port num our app
