apiVersion: v1
kind: Service
metadata:
  name: cluster-ip-service
  labels:
    app: redis
spec:
  type: ClusterIP
  ports:
    - name: redis-port
      port: 6379 #port of the service
      targetPort: 6379 
      protocol: TCP
  selector: # link
    app: redis