apiVersion: v1
kind: Service 
metadata:
 name: nginx-svc
 labels:
   app: nginx-svc
spec:
 type: NodePort # access to the world
 ports: 
  - name: http 
    port: 80 # this service port
    targetPort: 80 #the port of you container or targetport of the pods
    nodePort: 31089 # the port that enable in node to send to traffict
    protocol: TCP
 selector: #to link the lable from deployment.yml in nginx.yml
    app: deploy-app
     

