apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-app
  labels:
    app: deploy-app
spec:
  template:
    metadata:
      name: deploy-app
      labels:
        app: deploy-app
        # service: svc-app
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
  replicas: 3
  selector:
    matchLabels:
      app: deploy-app
      # service: svc-app