apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: webshop
    type: frontend
spec:
  template:
    metadata:
      name: my-first-pod
      labels:
        app: webshop
        type: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.8
  replicas: 5
  selector:
    matchLabels:
      type: frontend