#------------- create a presistent volume --------
apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab-pv
spec:
  hostPath: # mounts adirectory from the host node's filesystem into your Pod.
    path: /tmp/lab
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path #locally create a  PresistentVolume
