apiVersion: v1 # api kubernetes version
kind: Pod # kind of obj
metadata:
  name: healthy-pod #name of Pod 
  labels:
    app: goproxy #name of our app 
spec: # the pod require a container 
  containers:
  - name: healthy-container #name of our container
    image: nginx #the img from dockerhub
    livenessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 1
      failureThreshold: 5
      periodSeconds: 3
    readinessProbe:
      initialDelaySeconds: 5
      timeoutSeconds: 1
      failureThreshold: 7
      periodSeconds: 3