apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec: #this pressint volume
      volumes:
        - name: postgres-pv-claim
          persistentVolumeClaim:
             claimName: postgres-pv-claim
      containers:
        - image: postgres
          name: postgres
          env:
          - name: POSTGRES_USER
            value: "postgres"
          - name:  POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
          ports:
          - containerPort: 5432
          volumeMounts: #Create persistent volumes to store the data for the Postgres database
            - mountPath: /var/lib/postgresql/data
              name: postgres-pv-claim