apiVersion: apps/v1
kind: Deployment #first apply or create a deployment
metadata:
  name: vote # name of deployment service
  labels:
    app: vote # just a lable to fillter
spec: #This field tells us that we are creating three replicas of our pods
  replicas: 1 # num of rplica 
  selector: #This tells the object how to find the pods it will manage.
    matchLabels: #link the pod or find the pod 
      app: vote
  template: # It will look inside the pod template section and match the labels.
    metadata:
      labels: #The pods have the label app: vote
        app: vote
    spec: #This tells Kubernetes what to name our container
      containers:
        - image: mshaikh911/vote # Docker Hub , Kubernetes will pull this from there
          name: vote #name of container
          ports: # define the ports 
          - containerPort: 80 #This exposes port 80 on the container. 