apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  labels:
    app: worker
spec:
  replicas: 1
  selector:
    matchLabels: #link
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - image: mshaikh911/worker # img in dockerhub
          name: worker